### ISSUE TITLE
Pendências plugin

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#24]
# Resumo
Relacionado aos issues/prs:
- #13 

Existem algumas coisas pendentes no plugin!

# Pendências
- [x] questões de usuário (wp-admin e etc...) https://github.com/imobanco/WooCommerce-Imobanco/issues/15
- [ ] endereço com a atualização e número/complemento https://github.com/imobanco/WooCommerce-Imobanco/issues/16
- [x] busca de endereço existente https://github.com/imobanco/WooCommerce-Imobanco/issues/25
- [x] parcelamento https://github.com/imobanco/WooCommerce-Imobanco/issues/23
- [x] alteração no payload da notificação #26

**Comment by rodrigondec** [comment]
Esse issue foi passado para o @ibrunodev e foi solicitado uma estimativa de prazo!

**Comment by rodrigondec** [comment]
# Problemas encontrados

## Endereço
- [x] https://github.com/imobanco/WooCommerce-Imobanco/issues/25#issuecomment-703288236
- [ ] https://github.com/imobanco/WooCommerce-Imobanco/issues/16#issuecomment-703290051

## Parcelamento
- [x] https://github.com/imobanco/WooCommerce-Imobanco/issues/23#issuecomment-703293627
- [x] https://github.com/imobanco/WooCommerce-Imobanco/issues/23#issuecomment-703298285
